// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Message.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Messages {
  public static partial class EmployeeService
  {
    static readonly string __ServiceName = "EmployeeService";

    static readonly grpc::Marshaller<global::Messages.GetByBadgeNumberRequest> __Marshaller_GetByBadgeNumberRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.GetByBadgeNumberRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.EmpoleeResponse> __Marshaller_EmpoleeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.EmpoleeResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.GetAllRequest> __Marshaller_GetAllRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.GetAllRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.EmpoleeRequest> __Marshaller_EmpoleeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.EmpoleeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.AddPhotoRequest> __Marshaller_AddPhotoRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.AddPhotoRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.AddPhotoResponse> __Marshaller_AddPhotoResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.AddPhotoResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Messages.GetByBadgeNumberRequest, global::Messages.EmpoleeResponse> __Method_GetByBadgeNumber = new grpc::Method<global::Messages.GetByBadgeNumberRequest, global::Messages.EmpoleeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetByBadgeNumber",
        __Marshaller_GetByBadgeNumberRequest,
        __Marshaller_EmpoleeResponse);

    static readonly grpc::Method<global::Messages.GetAllRequest, global::Messages.EmpoleeResponse> __Method_GetAll = new grpc::Method<global::Messages.GetAllRequest, global::Messages.EmpoleeResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAll",
        __Marshaller_GetAllRequest,
        __Marshaller_EmpoleeResponse);

    static readonly grpc::Method<global::Messages.EmpoleeRequest, global::Messages.EmpoleeResponse> __Method_Save = new grpc::Method<global::Messages.EmpoleeRequest, global::Messages.EmpoleeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Save",
        __Marshaller_EmpoleeRequest,
        __Marshaller_EmpoleeResponse);

    static readonly grpc::Method<global::Messages.EmpoleeRequest, global::Messages.EmpoleeResponse> __Method_SaveAll = new grpc::Method<global::Messages.EmpoleeRequest, global::Messages.EmpoleeResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SaveAll",
        __Marshaller_EmpoleeRequest,
        __Marshaller_EmpoleeResponse);

    static readonly grpc::Method<global::Messages.AddPhotoRequest, global::Messages.AddPhotoResponse> __Method_AddPhoto = new grpc::Method<global::Messages.AddPhotoRequest, global::Messages.AddPhotoResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "AddPhoto",
        __Marshaller_AddPhotoRequest,
        __Marshaller_AddPhotoResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Messages.MessageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EmployeeService</summary>
    public abstract partial class EmployeeServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Messages.EmpoleeResponse> GetByBadgeNumber(global::Messages.GetByBadgeNumberRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task GetAll(global::Messages.GetAllRequest request, grpc::IServerStreamWriter<global::Messages.EmpoleeResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Messages.EmpoleeResponse> Save(global::Messages.EmpoleeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SaveAll(grpc::IAsyncStreamReader<global::Messages.EmpoleeRequest> requestStream, grpc::IServerStreamWriter<global::Messages.EmpoleeResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Messages.AddPhotoResponse> AddPhoto(grpc::IAsyncStreamReader<global::Messages.AddPhotoRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EmployeeService</summary>
    public partial class EmployeeServiceClient : grpc::ClientBase<EmployeeServiceClient>
    {
      /// <summary>Creates a new client for EmployeeService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EmployeeServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EmployeeService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EmployeeServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EmployeeServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EmployeeServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Messages.EmpoleeResponse GetByBadgeNumber(global::Messages.GetByBadgeNumberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetByBadgeNumber(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Messages.EmpoleeResponse GetByBadgeNumber(global::Messages.GetByBadgeNumberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetByBadgeNumber, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.EmpoleeResponse> GetByBadgeNumberAsync(global::Messages.GetByBadgeNumberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetByBadgeNumberAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.EmpoleeResponse> GetByBadgeNumberAsync(global::Messages.GetByBadgeNumberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetByBadgeNumber, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Messages.EmpoleeResponse> GetAll(global::Messages.GetAllRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Messages.EmpoleeResponse> GetAll(global::Messages.GetAllRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAll, null, options, request);
      }
      public virtual global::Messages.EmpoleeResponse Save(global::Messages.EmpoleeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Save(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Messages.EmpoleeResponse Save(global::Messages.EmpoleeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Save, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.EmpoleeResponse> SaveAsync(global::Messages.EmpoleeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.EmpoleeResponse> SaveAsync(global::Messages.EmpoleeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Save, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Messages.EmpoleeRequest, global::Messages.EmpoleeResponse> SaveAll(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveAll(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Messages.EmpoleeRequest, global::Messages.EmpoleeResponse> SaveAll(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SaveAll, null, options);
      }
      public virtual grpc::AsyncClientStreamingCall<global::Messages.AddPhotoRequest, global::Messages.AddPhotoResponse> AddPhoto(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPhoto(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Messages.AddPhotoRequest, global::Messages.AddPhotoResponse> AddPhoto(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_AddPhoto, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EmployeeServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EmployeeServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EmployeeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetByBadgeNumber, serviceImpl.GetByBadgeNumber)
          .AddMethod(__Method_GetAll, serviceImpl.GetAll)
          .AddMethod(__Method_Save, serviceImpl.Save)
          .AddMethod(__Method_SaveAll, serviceImpl.SaveAll)
          .AddMethod(__Method_AddPhoto, serviceImpl.AddPhoto).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EmployeeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetByBadgeNumber, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Messages.GetByBadgeNumberRequest, global::Messages.EmpoleeResponse>(serviceImpl.GetByBadgeNumber));
      serviceBinder.AddMethod(__Method_GetAll, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Messages.GetAllRequest, global::Messages.EmpoleeResponse>(serviceImpl.GetAll));
      serviceBinder.AddMethod(__Method_Save, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Messages.EmpoleeRequest, global::Messages.EmpoleeResponse>(serviceImpl.Save));
      serviceBinder.AddMethod(__Method_SaveAll, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Messages.EmpoleeRequest, global::Messages.EmpoleeResponse>(serviceImpl.SaveAll));
      serviceBinder.AddMethod(__Method_AddPhoto, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Messages.AddPhotoRequest, global::Messages.AddPhotoResponse>(serviceImpl.AddPhoto));
    }

  }
}
#endregion
